name: ci

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.32
      - name: Run remaining linters
        run: make lint

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Unit test
        run: make test
